workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    # integrations:
    #   app_store_connect: codemagic

    environment:
    #   ios_signing:
    #     distribution_type: app_store
    #     bundle_identifier: io.codemagic.sample.iosnative
    #   vars:
    #     BUNDLE_ID: "io.codemagic.sample.iosnative"
    #     XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Put the name of your Xcode workspace here
    #     XCODE_SCHEME: "CodemagicSample" # <-- Put the name of your Xcode scheme here
    #     APP_STORE_APPLE_ID: 1555555551
      xcode: latest
    #   cocoapods: default

    scripts:
      # Build the iOS app without code signing
      - name: Build ipa
        script: | 
          cd ./tassology && xcodebuild clean build \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      # Export IPA
      - name: Generate ipa
        script: |
          xcodebuild

    artifacts:
      - build/ios/ipa/*.ipa
